# Generated by Django 2.2.2 on 2019-07-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190617_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_product',
            field=models.BooleanField(default=False, verbose_name='горячее предложение'),
        ),
    ]
